### ISSUE TITLE
Compression gets started and runs out-of-memory although NOT selected

### ISSUE THREAD

**Issue by commsolid-dev** [nextcloud/backup#321]
Installation details:
- Nextcloud Docker container: official community edition
- Nextcloud version: 23.0.2
- Backup version: 1.0.6 
- Backup to external storage

an nfs volume is mounted to  the server and mapped into the container:
`xxx.yyy.com:/gdx_dr_backup_1          1.0T  362G  663G  36% /var/nextcloud/nxtcld/backup`

```
 app:
    image: nextcloud:23
    restart: unless-stopped
    volumes:
      - /var/nextcloud/nxtcld/html:/var/www/html
      - /var/nextcloud/nxtcld/config:/var/www/html/config
      - /var/nextcloud/nxtcld/data:/var/www/html/data
      - /var/nextcloud/nxtcld/backup:/var/www/html/backup
    environment:
```

```
www-data@56f419615897:~/html$ php occ backup:external:list
+-----------+--------------------------------------+------------------+
| StorageId | Path                                 | Storage Folder   |
+-----------+--------------------------------------+------------------+
| 388       | local::/var/www/html/backup/rpoints/ | restoring_points |
+-----------+--------------------------------------+------------------+
www-data@56f419615897:~/html$ php occ backup:external:appdata
Your appdata is currently on an external storage:
Storage Id: 389
Storage: local::/var/www/html/backup/tmpdata/
Root: app_data

www-data@56f419615897:~/html$
```

- Compression is NOT selected (but was once, then disabled)

following error message gets generated and system remains in maintenance mode:

`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 1052672 bytes) in /var/www/html/3rdparty/deepdiver/zipstreamer/src/ZipStreamer.php on line 359`
