### ISSUE TITLE
Error in cron.php since Nextcloud Version 29

### ISSUE THREAD

**Issue by mluettermann** [nextcloud/backup#663]
Since the NC 29 update, I've been receiving the following error message with Cron.php:

```
Error: Class "OC\BackgroundJob\TimedJob" not found in /var/www/html/custom_apps/backup/lib/Cron/Backup.php:48
Stack trace:
#0 /var/www/html/lib/composer/composer/ClassLoader.php(576): include()
#1 /var/www/html/lib/composer/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/html/c...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\Backup\\Cron...')
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(126): ReflectionClass->__construct('OCA\\Backup\\Cron...')
#4 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Backup\\Cron...')
#5 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(470): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Backup\\Cron...')
#6 /var/www/html/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Backup\\Cron...')
#7 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query('OCA\\Backup\\Cron...')
#8 /var/www/html/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get('OCA\\Backup\\Cron...')
#9 /var/www/html/lib/private/BackgroundJob/JobList.php(326): OCP\Server::get('OCA\\Backup\\Cron...')
#10 /var/www/html/lib/private/BackgroundJob/JobList.php(235): OC\BackgroundJob\JobList->buildJob(Array)
#11 /var/www/html/cron.php(163): OC\BackgroundJob\JobList->getNext(true)
#12 {main}
```

I'm using NC in a Docker environment

```yaml
version: '3.3'

services:
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-mariadb
    command: --transaction-isolation=READ-COMMITTED --innodb_read_only_compressed=OFF
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${FILES_LOCATION}/db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${root_pwd}
        MYSQL_PASSWORD: ${db_pwd}
        MYSQL_DATABASE: ${db_name}
        MYSQL_USER: ${db_user}
        MYSQL_INITDB_SKIP_TZINFO: ${MYSQL_INITDB_SKIP_TZINFO}
        MARIADB_AUTO_UPGRADE: ${MARIADB_AUTO_UPGRADE}
  
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    networks:
        - default
    restart: unless-stopped
    command: redis-server --requirepass ${db_pwd}
  
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
        MAINTENANCE_WINDOW_START: ${MAINTENANCE_WINDOW_START}
        TRUSTED_PROXIES: ${TRUSTED_PROXIES}
        OVERWRITEPROTOCOL: ${OVERWRITEPROTOCOL}
        OVERWRITECLIURL: ${OVERWRITECLIURL}
        OVERWRITEHOST: ${OVERWRITEHOST}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_HOST_PASSWORD: ${db_pwd}
        PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
        PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT}
    networks:
      - default
      - traefik_proxy
    volumes:
      - ${FILES_LOCATION}/nextcloud:/var/www/html
    restart: always
    labels:
        traefik.enable: true
        traefik.docker.network: traefik_proxy
        traefik.http.routers.nextcloud.rule: Host(`nextcloud.example.com`)
        traefik.http.routers.nextcloud.entrypoints: websecure
        traefik.http.routers.nextcloud.service: nextcloud
        traefik.http.services.nextcloud.loadbalancer.server.port: 80
        traefik.http.routers.nextcloud.middlewares: nextcloud_header,nextcloud_redirectregex
        traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent: true
        traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex: 'https://(.*)/.well-known/(?:card|cal)dav'
        traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement: 'https://$${1}/remote.php/dav'
        traefik.http.middlewares.nextcloud_header.headers.referrerPolicy: no-referrer
        traefik.http.middlewares.nextcloud_header.headers.stsSeconds: 31536000
        traefik.http.middlewares.nextcloud_header.headers.forceSTSHeader: true
        traefik.http.middlewares.nextcloud_header.headers.stsPreload: true
        traefik.http.middlewares.nextcloud_header.headers.stsIncludeSubdomains: true
        traefik.http.middlewares.nextcloud_header.headers.browserXssFilter: true
        traefik.http.middlewares.nextcloud_header.headers.customRequestHeaders.X-Forwarded-Proto: https
  
    
networks:
  traefik_proxy:
    external: true
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
     config:
       - subnet: "10.255.0.48/29"
         gateway: "10.255.0.49"
       - subnet: fd00::255:0:0:30/125
         gateway: fd00::255:0:0:31
```

After deactivating the backup app, the cron job is running normally again
